### ISSUE TITLE
Find the first block ever

### ISSUE THREAD

**Issue by wclr** [neodiX42/MyLocalTon#1]
Is it possible to get the details of the first block on the network?

**Comment by neodiX42** [comment]
The very first block is zero state and has seqno=0, blockchain does not return information about this block. The next very first generated block is (1,8000000000000000,-1). You can distinguish it from other blocks by mint message that is inside it. In MyLocalTon, sometimes on start you might not see this block, in this case simply scroll down and the missing block will be loaded.

**Comment by wclr** [comment]
I mean I would want to get info about the very first block, it should dated 15 nov 2019?

**Comment by neodiX42** [comment]
MyLocalTon is a local simulation of TON blockchain, you are addressing the wrong topic. The very first block of mainnet can be found here https://explorer.toncoin.org/search?workchain=-1&shard=8000000000000000&seqno=1&lt=&utime=&roothash=&filehash=

**Comment by wclr** [comment]
Thanks, I just couldn't find it in the explorer (which is linked on ton.org) https://ton.sh/block/-1/1 it doesn't display any useful data.
