### ISSUE TITLE
Add web app

### ISSUE THREAD

**Issue by Hid-K** [neodiX42/MyLocalTon#14]
I want to run this application in docker container and use it to test my smart-contracts and it would be cool if i would have ao access to UI via web.

**Comment by neodiX42** [comment]
In "Settings -> UI interface" you can enable Native blockchain explorer and then access it via browser at http://127.0.0.1:8000/last
Also, hopefully one day I will add ton-http-api https://github.com/neodiX42/MyLocalTon/issues/3

**Comment by Hid-K** [comment]
can i do it in some config to staticly enable this option?

**Comment by neodiX42** [comment]
Try to set **"enableBlockchainExplorer": true** in ./myLocalTon/settings.json

**Comment by Hid-K** [comment]
this didn't worked. browser can't connect to server. Scan with NMAP also said there is no port 8000 opened on 127.0.0.1

**Comment by neodiX42** [comment]
did you try to specify docker parameters `--network host` or `port-mapping (-p 8000:8000) `?

**Comment by Hid-K** [comment]
i did not runned it in docker yet. currently it is running on my machine

**Comment by neodiX42** [comment]
ok, do one test, please. Start MyLocalTon, wait till it starts the blockchain, go to the UI settings and enable Native blockchain explorer. Now restart MyLocalTon and on start check, if you see the explorer in the newly appeared menu "Explorer".
If you see the explorer, then the same will work from the browser.

![image](https://user-images.githubusercontent.com/52255577/213175370-edd499a0-86c3-4adc-9fb5-6bc001c7de5f.png)

**Comment by Hid-K** [comment]
explorer page is blank

**Comment by neodiX42** [comment]
I believe you have waited till the blocks started appearing in Blocks page.
What OS you are running on? It would be good if you could attach the logfile, mylocalton.log here.

**Comment by Hid-K** [comment]
[myLocalTon.log](https://github.com/neodiX42/MyLocalTon/files/10449347/myLocalTon.log)

**Comment by neodiX42** [comment]
Thanks!
I see the error.

`14:59:51.605 [JavaFX Application Thread] ERROR o.t.e.b.BlockchainExplorerExecutor - Cannot run program "/Users/hidk/Documents/Projects/MyLocalTonWEB/myLocalTon/genesis/bin/blockchain-explorer" (in directory "/Users/hidk/Documents/Projects/MyLocalTonWEB/myLocalTon/genesis/bin"): error=2, No such file or directory`

I will cross check if binaries are fine. Actually it is time to sync binaries with the TON master branch, will do that as well.

**Comment by neodiX42** [comment]
please try this version https://github.com/neodiX42/MyLocalTon/releases/tag/v67-main
