### ISSUE TITLE
Can't open it properly. Genesis is not ready.

### ISSUE THREAD

**Issue by howardpen9** [neodiX42/MyLocalTon#15]
![image](https://user-images.githubusercontent.com/36764495/221087440-5d85242f-4e36-443e-970f-09a18ae74f56.png)

![image](https://user-images.githubusercontent.com/36764495/221087499-15ed42e0-ef73-427f-9522-1e5232444377.png)

**Comment by neodiX42** [comment]
Could you please post your hardware details? (here or via telegram to me). Most probably you are running on a slow machine.
It would be also useful if you attach a full log file. You can get it by running: `java -jar MyLocalTon debug `
