### ISSUE TITLE
Not Run Properly

### ISSUE THREAD

**Issue by BarisCirika** [neodiX42/MyLocalTon#18]
Latest version don't run properly. Older version runs properly.

In App it shows that dialog box with info: 

> Initializing TON Blockchain very first time.
> It can take up to 2 minutes, please wait.

**But nothing happen i wait maybe 5 minutes.**

> Last log: 
> 17:56:46.857 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Detected OS: Mac OS X
> 17:56:46.886 [MyLocalTon - main] INFO  org.ton.utils.MyLocalTonUtils - isMacOsArm: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
> 
> 17:56:46.887 [MyLocalTon - main] INFO  org.ton.utils.Extractor - extracting ton-mac-x86_64.zip on macos

Terminal Output is:

> 17:56:44.495 [MyLocalTon - main] INFO  org.ton.main.Main - Starting application at path /Users/baris/Documents/myLocalTon/MyLocalTon.jar
> 17:56:46.854 [MyLocalTon - main] INFO  org.ton.main.App - myLocalTon config file location: /Users/baris/Documents/myLocalTon/myLocalTon/settings.json
> 17:56:46.857 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Working Directory =/Users/baris/Documents/myLocalTon
> 17:56:46.857 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Detected OS: Mac OS X
> 17:56:46.886 [MyLocalTon - main] INFO  org.ton.utils.MyLocalTonUtils - isMacOsArm: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
> 
> 17:56:46.887 [MyLocalTon - main] INFO  org.ton.utils.Extractor - extracting ton-mac-x86_64.zip on macos
> Tem 01, 2023 5:56:46 ÖS com.sun.javafx.application.PlatformImpl startup
> WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @4dca0ecd'

MacBook Pro: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz

**Comment by neodiX42** [comment]
Hi,
could you please remove myLocalTon folder and execute
`java -jar MyLocalTon.jar debug`
and show the log here or via pastebin.com e.g. ?

**Comment by BarisCirika** [comment]
> 8:47:12.029 [MyLocalTon - main] INFO  org.ton.main.Main - Starting application at path /Users/baris/Documents/myLocalTon/MyLocalTon.jar
> 18:47:14.014 [MyLocalTon - main] INFO  org.ton.main.App - myLocalTon config file location: /Users/baris/Documents/myLocalTon/myLocalTon/settings.json
> 18:47:14.017 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Working Directory = /Users/baris/Documents/myLocalTon
> 18:47:14.017 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Detected OS: Mac OS X
> 18:47:14.046 [MyLocalTon - main] INFO  org.ton.utils.MyLocalTonUtils - isMacOsArm: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
> 
> 18:47:14.047 [MyLocalTon - main] INFO  org.ton.utils.Extractor - extracting ton-mac-x86_64.zip on macos
> 18:47:14.048 [MyLocalTon - main] DEBUG org.ton.main.Main - UI Uncaught Exception in thread 'MyLocalTon - main': null
> Tem 01, 2023 6:47:14 ÖS com.sun.javafx.application.PlatformImpl startup
> WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @4dca0ecd'
> 18:47:14.049 [MyLocalTon - main] DEBUG org.ton.main.Main - java.lang.NullPointerException
> 	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
> 	at java.base/java.nio.file.Files.copy(Files.java:3128)
> 	at org.ton.utils.Extractor.extractMacBinaries(Extractor.java:194)
> 	at org.ton.utils.Extractor.extractBinaries(Extractor.java:71)
> 	at org.ton.utils.Extractor.<init>(Extractor.java:34)
> 	at org.ton.settings.Node.extractBinaries(Node.java:83)
> 	at org.ton.main.App.main(App.java:139)
> 	at org.ton.main.Main.main(Main.java:45)
> 
> 18:47:14.256 [JavaFX Application Thread] DEBUG org.ton.main.App - Starting application
> 18:47:16.309 [JavaFX Application Thread] DEBUG org.ton.main.App - onShown, stage loaded

**Comment by neodiX42** [comment]
please try release https://github.com/neodiX42/MyLocalTon/releases/tag/v73-main

**Comment by BarisCirika** [comment]
Not a chance.

> baris@Bars-MBP myLocalTon % java -jar MyLocalTon.jar debug
> 21:02:34.846 [MyLocalTon - main] INFO  org.ton.main.Main - Starting application at path /Users/baris/Documents/myLocalTon/MyLocalTon.jar
> 21:02:36.493 [MyLocalTon - main] INFO  org.ton.main.App - myLocalTon config file location: /Users/baris/Documents/myLocalTon/myLocalTon/settings.json
> 21:02:36.495 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Working Directory = /Users/baris/Documents/myLocalTon
> 21:02:36.495 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Detected OS: Mac OS X
> 21:02:36.507 [MyLocalTon - main] INFO  org.ton.utils.MyLocalTonUtils - isMacOsArm: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
> 
> 21:02:36.508 [MyLocalTon - main] INFO  org.ton.utils.Extractor - extracting ton-mac-x86_64.zip on macos
> 21:02:36.509 [MyLocalTon - main] DEBUG org.ton.main.Main - UI Uncaught Exception in thread 'MyLocalTon - main': null
> 21:02:36.510 [MyLocalTon - main] DEBUG org.ton.main.Main - java.lang.NullPointerException
> 	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
> 	at java.base/java.nio.file.Files.copy(Files.java:3128)
> 	at org.ton.utils.Extractor.extractMacBinaries(Extractor.java:194)
> 	at org.ton.utils.Extractor.extractBinaries(Extractor.java:71)
> 	at org.ton.utils.Extractor.<init>(Extractor.java:34)
> 	at org.ton.settings.Node.extractBinaries(Node.java:83)
> 	at org.ton.main.App.main(App.java:139)
> 	at org.ton.main.Main.main(Main.java:45)
> 
> Tem 01, 2023 9:02:36 ÖS com.sun.javafx.application.PlatformImpl startup
> WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @4dca0ecd'
> 21:02:36.610 [JavaFX Application Thread] DEBUG org.ton.main.App - Starting application
> 21:02:38.402 [JavaFX Application Thread] DEBUG org.ton.main.App - onShown, stage loaded

**Comment by neodiX42** [comment]
Give it a try to v76 please

**Comment by BarisCirika** [comment]
Different error now.

> 23:47:47.185 [MyLocalTon - main] INFO  org.ton.main.Main - Starting application at path /Users/baris/Documents/myLocalTon/MyLocalTon.jar
> 23:47:48.858 [MyLocalTon - main] INFO  org.ton.main.App - myLocalTon config file location: /Users/baris/Documents/myLocalTon/myLocalTon/settings.json
> 23:47:48.861 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Working Directory = /Users/baris/Documents/myLocalTon
> 23:47:48.861 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Detected OS: Mac OS X
> 23:47:48.878 [MyLocalTon - main] INFO  org.ton.utils.MyLocalTonUtils - isMacOsArm: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
> 
> 23:47:48.879 [MyLocalTon - main] INFO  org.ton.utils.Extractor - extracting ton-mac-x86_64.zip on macos
> Tem 01, 2023 11:47:48 ÖS com.sun.javafx.application.PlatformImpl startup
> WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @4dca0ecd'
> 23:47:48.997 [JavaFX Application Thread] DEBUG org.ton.main.App - Starting application
> 23:47:50.496 [MyLocalTon - main] DEBUG org.ton.utils.Extractor - mac binaries path: /Users/baris/Documents/myLocalTon/myLocalTon/genesis/bin
> 23:47:50.501 [MyLocalTon - main] DEBUG org.ton.db.DbPool - Spawning new DB d2bd51a7-3569-41de-867a-941defef4bc1
> 23:47:50.582 [MyLocalTon - main] DEBUG org.ton.db.DB2 - DB d2bd51a7-3569-41de-867a-941defef4bc1 initialized.
> 23:47:50.618 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Working Directory = /Users/baris/Documents/myLocalTon
> 23:47:50.618 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Binaries already extracted.
> 23:47:50.619 [MyLocalTon - main] DEBUG o.ton.executors.dhtserver.DhtServer - publicIpNum 2130706433
> 23:47:50.620 [MyLocalTon - main] INFO  o.ton.executors.dhtserver.DhtServer - Initializing DHT server
> 23:47:50.624 [MyLocalTon - main] DEBUG o.t.e.dhtserver.DhtServerExecutor - execute: /Users/baris/Documents/myLocalTon/myLocalTon/genesis/bin/dht-server -v 4 -t 1 -C /Users/baris/Documents/myLocalTon/myLocalTon/templates/example.config.json -l /Users/baris/Documents/myLocalTon/myLocalTon/genesis/db/dht-server/2023.07.01_23-47-50 -D /Users/baris/Documents/myLocalTon/myLocalTon/genesis/db/dht-server/ -I 127.0.0.1:6302
> 23:47:50.982 [JavaFX Application Thread] DEBUG org.ton.main.App - onShown, stage loaded
> 23:47:51.019 [DHT server on genesis] INFO  o.t.e.dhtserver.DhtServerExecutor - dht-server-genesis stopped
> 23:47:51.019 [MyLocalTon - main] DEBUG o.ton.executors.dhtserver.DhtServer - dht-server result: dyld[998]: Library not loaded: /nix/store/0d4w6hxjncsm1x4ayzji5wrj6pcwcdyz-libcxx-11.1.0/lib/libc++.1.0.dylib
>   Referenced from: <no uuid> /Users/baris/Documents/myLocalTon/myLocalTon/genesis/bin/dht-server
>   Reason: tried: '/nix/store/0d4w6hxjncsm1x4ayzji5wrj6pcwcdyz-libcxx-11.1.0/lib/libc++.1.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/nix/store/0d4w6hxjncsm1x4ayzji5wrj6pcwcdyz-libcxx-11.1.0/lib/libc++.1.0.dylib' (no such file), '/nix/store/0d4w6hxjncsm1x4ayzji5wrj6pcwcdyz-libcxx-11.1.0/lib/libc++.1.0.dylib' (no such file), '/usr/local/lib/libc++.1.0.dylib' (no such file), '/usr/lib/libc++.1.0.dylib' (no such file, not in dyld cache)
> 
> 23:47:51.120 [MyLocalTon - main] ERROR o.ton.executors.dhtserver.DhtServer - Initialization of DHT server failed. File /Users/baris/Documents/myLocalTon/myLocalTon/genesis/db/dht-server/config.json was not created.
> 23:47:51.121 [Thread-0] DEBUG org.ton.main.Main - Shutdown hook triggered...
> 23:47:51.122 [Thread-0] DEBUG org.ton.utils.MyLocalTonUtils - Do shutdown
> 23:47:51.122 [Thread-0] INFO  org.ton.db.DbPool - Closing database...
> 23:47:51.123 [Thread-0] INFO  org.ton.utils.MyLocalTonUtils - Destroying external processes...
> java.util.concurrent.RejectedExecutionException: Task com.sun.javafx.tk.quantum.PaintRenderJob@5af7f1a8[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@7e0ecfef[Wrapped task = com.sun.javafx.tk.quantum.PresentingPainter@537d15ec]] rejected from com.sun.javafx.tk.quantum.QuantumRenderer@79e143a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
> 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
> 	at com.sun.javafx.tk.quantum.QuantumRenderer.submitRenderJob(QuantumRenderer.java:221)
> 	at com.sun.javafx.tk.quantum.QuantumToolkit.addRenderJob(QuantumToolkit.java:487)
> 	at com.sun.javafx.tk.quantum.ViewScene.repaint(ViewScene.java:141)
> 	at com.sun.javafx.tk.quantum.PaintCollector.renderAll(PaintCollector.java:442)
> 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:576)
> 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
> 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
> 	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:353)
> 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
> 23:47:52.140 [Thread-0] DEBUG org.ton.utils.MyLocalTonUtils - Waiting for processes to be killed...

**Comment by neodiX42** [comment]
Now it should work, please try release v77

**Comment by BarisCirika** [comment]
Blocks and transactions are working but validation and accounts are not.
Total size also not shown.
Accounts tab shows starting... text.
Validation tab has ping pong animation.

I wait maybe 5 minutes.

**Comment by neodiX42** [comment]
Could you please try version 83?

**Comment by BarisCirika** [comment]
Everything is okay now. Thank you for your interest.
