### ISSUE TITLE
Graphical User Interface not Starting Instead its on Visual Interface ?????

### ISSUE THREAD

**Issue by host2india** [neodiX42/MyLocalTon#21]
18:36:22.315 [MyLocalTon - Dump Block 352] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,353)
18:36:23.308 [MyLocalTon - Dump Block 353] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,354)
18:36:24.305 [MyLocalTon - Dump  Block 354] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,355)
18:36:26.317 [MyLocalTon - Dump Block 355] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,356)
18:36:27.319 [MyLocalTon - Dump Block 356] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,357)
18:36:28.330 [MyLocalTon - Dump Block 357] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,358)
18:36:29.336 [MyLocalTon - Dump Block 358] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,359)
18:36:31.319 [MyLocalTon - Dump Block 359] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,360)
18:36:32.331 [MyLocalTon - Dump Block 360] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,361)
18:36:33.337 [MyLocalTon - Dump Block 361] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,362)
18:36:35.344 [MyLocalTon - Dump Block 362] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,363)
18:36:36.332 [MyLocalTon - Dump Block 363] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,364)
18:36:37.334 [MyLocalTon - Dump Block 364] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,365)
18:36:39.329 [MyLocalTon - Dump Block 365] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,366)
18:36:40.331 [MyLocalTon - Dump Block 366] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,367)
Its working but the problem is visual interface only not graphical interface coming
![issue](https://github.com/neodiX42/MyLocalTon/assets/15612818/0c53fe85-ded8-45e0-a76d-8e9474ee3e77)

**Comment by neodiX42** [comment]
Could you please show which version of Java you are running (`java --version`)?
Make also sure you haven't installed headless Java.

**Comment by neodiX42** [comment]
come back if you still have it
