### ISSUE TITLE
ton4j version is not up-to-date

### ISSUE THREAD

**Issue by bitgorust** [neodix42/MyLocalTon#28]
The newest version of ton4j in https://github.com/neodix42/ton4j is `0.4.7`, but `ton4j.version` here https://github.com/neodix42/MyLocalTon/blob/main/pom.xml is still `0.1.4`, does it make sense?

**Comment by neodix42** [comment]
This is not a problem and MyLocalTon works fine. 
I have it already in my backlog - to upgrade ton4j in MyLocalTon.
