### ISSUE TITLE
Please ship also ton-http-api with this tool

### ISSUE THREAD

**Issue by dariotarantini** [neodiX42/MyLocalTon#3]
i think could be useful to ship also https://github.com/toncenter/ton-http-api with this tool. Also a cli-only version of this tool could be useful (just like ganache-cli)

**Comment by neodiX42** [comment]
ton-http-api is a standalone application from TonCenter and requires Python deployment. It does not make much sense if we ship it together with MyLocalTon. At the same time, we plan to support command line only option of MyLocalTon. It will be able to run with headless java and won't have any GUI. Simple configuration parameters will be availabe via command line parameters.

**Comment by neodiX42** [comment]
Ok, there some more requests for this feature. I will keep an eye on it and put whenever have time.

**Comment by kdimentionaltree** [comment]
Hi, we currently working on _ton-http-api_ update which allows to run it locally on any machine (now only Ubuntu is supported).
Also _ton-http-api_ will soon be available on PyPi.
I'll report here on updates.
