### ISSUE TITLE
CLI \ API tool to create transaction

### ISSUE THREAD

**Issue by dkatzan** [neodix42/MyLocalTon#31]
Hi, thx for this tool 
I'm planning to use MyLocalTon in order to test some wallet app I'm building

trying to build a docker file to run everything I need, but in order to run my tests I will need some kind of faucet functionality 
When running MyLocalTon in the UI, going into accounts, I see u start off with multiple funded wallets, and can use those in order to send transactions to a destination of your choice

Is it possible to access and control those using CLI or some API?

**Comment by neodix42** [comment]
Hi, 
there is no such option now. 
This is a valid point and it is my backlog, hopefully, within a month or two, I will add it.
For now, you can take a look at the secret phrases and private keys in `settings.json` file.

**Comment by dkatzan** [comment]
Ah, got you thx

I see in settings.json the following:

```
  "mainWalletAddrBase64": "kf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIue",
  "mainWalletAddrFull": "-1:0000000000000000000000000000000000000000000000000000000000000000",
  "mainWalletPrvKey": "b737ef573c6d85367372777e14aee3e62e306fb16bef3dbe13fc8f3de946dcf9",
```
are u suggesting I can extract the private key from there, and use that to programmatically create a transaction

**Comment by neodix42** [comment]
That's right.
You can also take validator's wallet - see section
genesisNode.walletAddress - this wallet has the mnemonic.
For programmatically to work with wallets/smart contracts you can use one
of the following libs:

goutils - go
***@***.*** - javascript
ton-kotlin
pytoniq
ton4j - java
