### ISSUE TITLE
Running ton-http-api

### ISSUE THREAD

**Issue by dkatzan** [neodix42/MyLocalTon#32]
I'm trying to run MyLocalTon in a docker, together with ton-http-api

and am hitting some issues, 
I saw there is a UI option to install and enable it, but not sure I can trigger it without UI? is there some setting \ config option such that it will start MyLocalTon along with ton-http-api

otherwise, I'm trying to manually run ton-http-api from command line after installing it, which obviously fails since it can't connect due to the list server 
`TonlibWorker #009 report_archival exception of type TonlibError: LITE_SERVER_NETWORK`
IIUC, it is becuse it is trying to connect to the default list of testnet\mainnet network?

Not sure, how I can configure it to connect to my running local ton

their [instructions](https://github.com/toncenter/ton-http-api?tab=readme-ov-file#how-to-point-the-service-to-my-own-lite-server), state to change the list of lite servers in the config file, but not sure how exactly to change that

Thx!

**Comment by dkatzan** [comment]
awesome, that will be really helpful for us
will try what you suggested for now

**Comment by dkatzan** [comment]
Updating that this worked for me, 
would still love to see this is as a command line argument to avoid this "hack" if possible

anyway, thx for the quick responses

**Comment by dkatzan** [comment]
hmm, might be a bit difficult \ hacky to achieve this, I will need to run MyLocalTon as part of the docker build, wait for settings file to be created, take it down and edit the file on the fly

**Comment by neodix42** [comment]
A new release will be out today.
