### ISSUE TITLE
Using wallet as a faucet

### ISSUE THREAD

**Issue by dkatzan** [neodix42/MyLocalTon#35]
Following up on this request https://github.com/neodix42/MyLocalTon/issues/31

it looks like both the main wallet and the validator wallet in the settings file are constantly creating new transactions, causing their seqno to keep increasing

using one of these wallets as faucet can easily result in a race where my transaction fail due to old seqno?

would it be possible to add another wallet which is funded with a lot of ton at bootstrap, and his details added to the settings file as well to serve as a potential faucet wallet?

Would it be possible to make such a wallet with a preset hardcoded private key and address, so it can be used in test setup, without having to extract it from setting file each time?

Thx again for the help!

**Comment by neodix42** [comment]
I found no reason why this could not be implemented. Please try release [MyLocalTon v113](https://github.com/neodix42/MyLocalTon/releases/tag/v113).
You will be able to find raw address and the mnemonic of faucet wallet in a console output, as well as [here ](https://github.com/neodix42/MyLocalTon/blob/main/src/main/java/org/ton/settings/MyLocalTonSettings.java#L139).

**Comment by dkatzan** [comment]
How would you use the private key to init a wallet, e.g. in pytoniq
I managed to do it using the menomics, 
but looking at the private key, it looks to be 64 char long and in hex format, which are 32 bytes
but `pytoniq.from_private_key` actually expects private key to be 64 bytes

**Comment by neodix42** [comment]
I don't know how exactly to do it in pytoniq, but in general you have first to create a signature key pair from seed.
Here is an example with [ton4j](https://github.com/neodix42/ton4j/blob/014bfd83edf444e1ec92e339f6d7ddf3e4def240/utils/src/main/java/org/ton/java/utils/Utils.java#L583).
Basically use ed25519.FromSeed(32bytes) and as result will be 64 bytes secret, that can be used later on.

**Comment by dkatzan** [comment]
Ahh got u
so in pythoniq it the private key can be obtained by using 
```
from nacl.bindings import crypto_sign_seed_keypair
public_key, private_key = crypto_sign_seed_keypair(seed)
```
