### ISSUE TITLE
Exit code 33

### ISSUE THREAD

**Issue by dkatzan** [neodix42/MyLocalTon#41]
Hi @neodix42 ,
We are running multiple tests using the local Ton version, and each test on it's own is using the faucet in order to initialize a fresh address with some funds for the purpose of the test

I'm trying to make these test run in parallel, to reduce our tests time, and am encountering some issues around nonces

at first, I tried locking the init phase where I load the funds, and only release it once I ensured the nonce has increased..
but since each tests is doing at least 2 such load (once for Ton and once for Jetton), and each such transaction takes around 5 sec, tests had too much effect on each other..

I then tried to manage the nonce myself, and only lock the part where I pick the nonce and use it
but once I tried to send a transaction with nonce 3, while a transaction with nonce 2 was not yet included on-chain (but was sent to the node), the request failed with an err

```
pytoniq.liteclient.client.LiteServerError: Liteserver crashed with 0 code. Message: cannot apply external message to current state : External message was not accepted
Cannot run message on account: inbound external message rejected by transaction A560DC2F757589A7152835573D23117910207DDEDEFA717DBC82D8CF932E31B2:
exitcode=33, steps=33, gas_used=0
```

according to the docs, https://docs.tact-lang.org/book/exit-codes/#33 I should only encounter it after pushing 256 transactions, but I encounter it already on the second push

any idea? might it be related to a different config in MyLocalTon?

**Comment by neodix42** [comment]
Hi, you forgot to mention the version of the wallet you are using. 
Initially, I thought you were using highload-wallet, but it might be that you are using a regular wallet like v1-v5, in that case, you probably get an error in Compute Phase, not in Action Phase and that means you are simply sending seqno that was used before and need to review logic of your test.

**Comment by dkatzan** [comment]
Hi, I'm using WalletV3R2 (which is the default faucet wallet provided with the node)

Are u suggestion this is the error u would also expected to see in case I try to send a message with nonce X after a different message with nonce X was already sent? 

I'll try double checking myself

**Comment by dkatzan** [comment]
Well, I took another look, and looks like my implementation was correct, 
I'm sending a transaction with nonce 2, and then trying to send a transaction with nonce 3 will error, until the transaction with nonce 2 gets included in the chain (and `getseqno` returns 3) and then trying to send it will succeed

based on [this](https://gealber.com/ton-virtual-machine-exit-code-33) and [this](https://github.com/xssnick/tonutils-go/issues/229 ) it looks it is in fact not meant to work
