### ISSUE TITLE
Validator engine does not exist

### ISSUE THREAD

**Issue by psylopunk** [neodiX42/MyLocalTon#6]
This file is not in [binaries archive](https://github.com/neodiX42/MyLocalTon/blob/main/src/main/resources/org/ton/binaries/macos-arm64.zip), which leads to an error:
`06:49:26.171 [MyLocalTon - main] ERROR o.t.e.v.ValidatorEngineExecutor - Cannot run program "/Users/psylopunk/myLocalTon/genesis/bin/validator-engine" (in directory "/Users/psylopunk/myLocalTon/genesis/bin"): error=2, No such file or directory`

**Comment by neodiX42** [comment]
Thanks for reporting. Fixed with release [v16-arm64-aarch64](https://github.com/neodiX42/MyLocalTon/releases/tag/v16-arm64-aarch64)

**Comment by psylopunk** [comment]
Thank you so much, it worked
